# This is a basic workflow to help you get started with Actions

name: fetch-pins-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup git config
        run: |
          git config user.name "_bot"
          git config user.email "<>"
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          pip3 install -r requirements.txt
          python3 downloader.py https://www.pinterest.jp/atulvinayak/pins/ -j 16 -d docs/images
          python3 generate.py
          git add -A
          git commit -am "_" 
          sleep 3 
          git push
          
