name: Elixir Project and Publish

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * 0' # Runs every week
  push:
    branches:
      - master # Push to master trigger

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: 25.0.0
        elixir-version: 1.14.0

    - name: Install dependencies
      run: mix deps.get

    - name: Run Elixir project
      run: mix underscore
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_HOST: ${{ secrets.CLOUDFLARE_HOST }}

    - name: Commit changes in 'docs' folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./docs
        git diff --quiet && git diff --staged --quiet || git commit -m "_"
        git push --force

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
